#### 1. Load the CSV file using Pandas and display the first 10 rows.

In [2]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\messy_customer_loan_dataset - messy_customer_loan_dataset.csv")
df

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37,297809,698,Self-Employed,12th,Married,Mumbai,Mass,Education,378342,60,3,0.258,No
1,CUST100077,36,1048283,874,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792,48,11,0.558,Yes
2,CUST100317,55,1043481,661,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792,84,4,NaN,Yes
3,CUST101041,54,369591,722,Salaried,Graduate,Single,Kolkata,Premium,Home,908250,84,10,0.356,Yes
4,CUST101358,27,666989,727,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370,72,4,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40,477723,719,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455,48,NaN,0.569,No
1531,CUST101295,65,1394481,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828,120,8,0.344,Yes
1532,CUST100861,66,NaN,686,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9,0.084,Yes
1533,CUST101460,45,543340,720,Business,Graduate,Married,Pune,Mass,Education,302389,72,9,0.089,No
1534,CUST101127,61,NaN,731,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995,12,5,0.259,No

In [3]:
df.head(10)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37,297809,698,Self-Employed,12th,Married,Mumbai,Mass,Education,378342,60,3,0.258,No
1,CUST100077,36,1048283,874,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792,48,11,0.558,Yes
2,CUST100317,55,1043481,661,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792,84,4,NaN,Yes
3,CUST101041,54,369591,722,Salaried,Graduate,Single,Kolkata,Premium,Home,908250,84,10,0.356,Yes
4,CUST101358,27,666989,727,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370,72,4,0.169,Yes
5,CUST100925,32,317590,690,Salaried,Graduate,M,Mumbai,Premium,Auto,235549,120,5,0.46,No
6,CUST100758,39,322966,707,Contract,Graduate,Married,Chennai,Mass,Personal,563319,24,7,0.323,No
7,CUST100793,54,999108,689,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783,48,NaN,0.233,Yes
8,CUST100965,65,478191,758,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872,72,5,0.375,No
9,CUST101198,67,1063307,774,SALARIED,Graduate,Married,Jaipur,Affluent,Home,549693,120,2,0.394,Yes

#### 2. Display the number of rows and columns in the dataset.

In [4]:
df.shape

(1535, 15)

#### 3. Display all column names and identify which column names have
#### leading/trailing spaces.

In [6]:
print(df.columns.tolist())
for col in df.columns:
    if col != col.strip():
        print(repr(col))
for col in df.columns:
    print(col)

['Customer ID', 'Age', 'Annual Income', 'credit Score', 'Employment-Type', 'Education  Level', 'marital_status', 'city', 'customer_segment', 'loan_type', 'Loan Amount (INR)', 'tenure Months', 'Monthly Visits', 'debt_to_income', 'Loan Approved?']
Customer ID
Age
Annual Income
credit Score
Employment-Type
Education  Level
marital_status
city
customer_segment
loan_type
Loan Amount (INR)
tenure Months
Monthly Visits
debt_to_income
Loan Approved?

#### 4. Clean all column names by removing extra spaces and converting them into a
#### consistent format such as snake_case.

In [13]:
df.columns =(df.columns.str.strip().str.lower().str.replace(" ", "_"))
print(df.columns)

Index(['customer_id', 'age', 'annual_income', 'credit_score',
       'employment-type', 'education__level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'loan_amount_(inr)', 'tenure_months',
       'monthly_visits', 'debt_to_income', 'loan_approved?'],
      dtype='object')

#### 5. Check the data type of every column.

In [14]:
df.dtypes

customer_id          object
age                  object
annual_income        object
credit_score         object
employment-type      object
education__level     object
marital_status       object
city                 object
customer_segment     object
loan_type            object
loan_amount_(inr)    object
tenure_months         int64
monthly_visits       object
debt_to_income       object
loan_approved?       object
dtype: object

#### 6. Find the total number of missing values in each column.

In [15]:
df.isnull().sum()

customer_id            0
age                   71
annual_income         84
credit_score          77
employment-type       60
education__level      46
marital_status         0
city                  52
customer_segment       0
loan_type              0
loan_amount_(inr)    102
tenure_months          0
monthly_visits        55
debt_to_income        89
loan_approved?         0
dtype: int64

#### 7. Find the percentage of missing values in each column.

In [22]:
df.isnull().sum()/len(df)*100

customer_id          0.000000
age                  4.625407
annual_income        5.472313
credit_score         5.016287
employment-type      3.908795
education__level     2.996743
marital_status       0.000000
city                 3.387622
customer_segment     0.000000
loan_type            0.000000
loan_amount_(inr)    6.644951
tenure_months        0.000000
monthly_visits       3.583062
debt_to_income       5.798046
loan_approved?       0.000000
dtype: float64

#### 8. Find all rows where Age is missing.

In [28]:
df["age"].isna().sum()

np.int64(71)

#### 9. Find all rows where Annual Income is missing.

In [23]:
df["annual_income"].isna().sum()

np.int64(84)

#### 10.Remove completely duplicate rows and report how many duplicate rows were
#### removed.

In [29]:
duplicate_count = df.duplicated().sum()

df = df.drop_duplicates()
duplicate_count

np.int64(35)

#### 11.The Age column contains numbers as well as values like "unknown" and
#### "twenty five". Clean this column and convert it into a proper numeric column.

In [31]:
pd.to_numeric(df["age"], errors="coerce")
df["age"]

0       37.0
1       36.0
2       55.0
3       54.0
4       27.0
        ...
1530    40.0
1531    65.0
1532    66.0
1533    45.0
1534    61.0
Name: age, Length: 1500, dtype: float64

#### 12.The Annual Income column contains values such as 650000 INR, ₹720000,
#### 1.2L, and N/A. Clean the column and convert the valid values into numeric
#### format.

In [41]:
pd.to_numeric(df["annual_income"], errors="coerce")

0        297809.0
1       1048283.0
2       1043481.0
3        369591.0
4        666989.0
          ...
1530     477723.0
1531    1394481.0
1532          NaN
1533     543340.0
1534          NaN
Name: annual_income, Length: 1500, dtype: float64

#### 13.Clean the Credit Score column and identify values that cannot be converted
#### into numbers.

In [43]:
credit_score_numeric =m.pd.to_numeric(df["credit_score"],errors="coerce")
print(df.loc[credit_sco/re_numeric.isna(),"credit_score"].unique())

[nan 'unknown' 'seven hundred' '720 points']

#### 14.The Loan Amount column contains currency symbols, text, and numeric
#### values. Remove the unwanted characters and convert it into numeric format.

In [49]:
pd.to_numeric(df["loan_amount_(inr)"].astype(str).str.replace(r"[₹$,\s]", "", regex=True),errors="coerce")bb

0         378342.0
1         751792.0
2         892792.0
3         908250.0
4         386370.0
           ...
1530     1106455.0
1531      222828.0
1532    50000000.0
1533      302389.0
1534      753995.0
Name: loan_amount_(inr), Length: 1500, dtype: float64

#### 15.The Monthly Visits column contains values such as "five", "N/A", and "-".
#### Convert valid values into numeric values and handle invalid values.

In [50]:
pd.to_numeric(df["monthly_visits"], errors="coerce")

0        3.0
1       11.0
2        4.0
3       10.0
4        4.0
        ...
1530     NaN
1531     8.0
1532     9.0
1533     9.0
1534     5.0
Name: monthly_visits, Length: 1500, dtype: float64

#### 16.Clean the Debt to Income column where some values are written like 35%
#### and 0.4x. Convert the valid values into a consistent numeric format.

In [52]:
def clean_dti(x):
    x = str(x).strip()

    if x.endswith("%"):
        return float(x[:-1]) / 100

    if x.endswith("x"):
        return float(x[:-1])

    return pd.to_numeric(x, errors="coerce")

df["debt_to_income"].apply(clean_dti)

0       0.258
1       0.558
2         NaN
3       0.356
4       0.169
        ...
1530    0.569
1531    0.344
1532    0.084
1533    0.089
1534    0.259
Name: debt_to_income, Length: 1500, dtype: float64

#### 17.After cleaning the numerical columns, check which columns are still stored as
#### object data type.

In [56]:
df.select_dtypes(include="object").columns

Index(['customer_id', 'credit_score', 'employment-type', 'education__level',
       'marital_status', 'city', 'customer_segment', 'loan_type',
       'monthly_visits', 'loan_approved?'],
      dtype='object')

#### 18.Find all unique values in the Employment-Type column.

In [55]:
df["employment-type"].unique

<bound method Series.unique of 0       Self-Employed
1            Contract
2       Self-Employed
3            Salaried
4       Self-Employed
            ...
1530    Self-Employed
1531    Self-Employed
1532         Contract
1533         Business
1534         Salaried
Name: employment-type, Length: 1500, dtype: object>

#### 19.Standardize the Employment-Type column so that values such as salaried,
#### SALARIED, and Salaried become one consistent value.

In [60]:
df["employment-type"].str.strip().str.lower()

print(df["employment-type"].unique())

['self-employed' 'contract' 'salaried' 'self employed' 'business' nan
 'unknown']

#### 20.Clean the Education Level column and make values such as graduate,
#### GRADUATE, and Graduate consistent.

In [63]:
df["education__level"].str.strip().str.lower()

print(df["education__level"].unique())

['12th' 'Graduate' 'Postgraduate' 'Diploma' nan 'Post Graduate' 'Other'
 'GRADUATE' 'postgraduate' 'graduate']

#### 21.Clean the City column. Identify incorrect or inconsistent values such as
#### hyderbad, Hyd, Bangalore, and Bengaluru.

In [66]:
df["city"].str.strip().str.lower()

df["city"].replace({
    "hyderbad": "hyderabad",
    "hyd": "hyderabad",
    "bengaluru": "bangalore"
})
df["city"].unique()

array(['mumbai', 'jaipur', 'kolkata', 'hyderabad', 'chennai', 'bangalore',
       nan, 'delhi', 'pune'], dtype=object)

#### 22.Find all unique values in the Customer Segment column and identify invalid
#### categories.

In [70]:
valid_categories = ["premium", "standard", "basic"]
df["customer_segment"].astype(str).str.strip().str.lower()
df.loc[~df["customer_segment"].isin(valid_categories),"customer_segment"].unique()
invalid_values

array(['mass', 'affluent', 'sme', 'unknown', 'high value'], dtype=object)