In [69]:
import pandas as pd

In [70]:
df = pd.read_csv("C:\\Users\\HP\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

#### Challenge 1 – Complete Data Cleaning
#### Your manager gives you a messy dataset.
#### Perform all of the following:
#### • Load the dataset.
#### • Display dataset information.
#### • Find missing values.
#### • Remove duplicate rows.
#### • Fill missing values:
#### o Age → median
#### o Balance → mean
#### • Rename:
#### o Target → CustomerStatus
#### o AnnualIncome → Income
#### • Display the first 15 rows.
#### Methods expected:
#### read_csv()
#### info()
#### isnull()
#### drop_duplicates()
#### median()
#### mean()
#### fillna()
#### rename()
#### head()

In [72]:
import pandas as pd

df = pd.read_csv("C:\\Users\\HP\\Downloads\\Task_dataset - Task_dataset.csv")

df.info()

print("Missing Values:")
print(df.isnull().sum())


df["Age"] = df["Age"].fillna(df["Age"].median())

df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

df = df.rename(columns={
    "Target": "CustomerStatus",
    "AnnualIncome": "Income"
})

df.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
Missing Values:
CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

#### Challenge 2 – Banking Report
#### The bank wants a numeric report.
#### Tasks
#### • Select only numeric columns.
#### • Display summary statistics.
#### • Convert Age and CreditScore to float.
#### • Display information again.

In [ ]:
import pandas as pd

df = pd.read_csv("C:\\Users\\HP\\Downloads\\Task_dataset - Task_dataset.csv")

numeric_df = df.select_dtypes(include="number")

print(numeric_df)

print(numeric_df.describe())

df["Age"] = df["Age"].astype(float)
df["CreditScore"] = df["CreditScore"].astype(float)

df.info()

#### Challenge 3 – Duplicate Investigation
#### Find duplicate customers.
#### Then
#### • Count duplicate rows.
#### • Remove duplicates.
#### • Print information before and after removing duplicates.
#### • Show the last 20 rows.

In [ ]:
import pandas as pd

df = pd.read_csv("C:\\Users\\HP\\Downloads\\Task_dataset - Task_dataset.csv")

print("Information Before Removing Duplicates:")
df.info()

duplicate_count = df.duplicated().sum()

print("\nNumber of Duplicate Rows:", duplicate_count)

print("\nDuplicate Rows:")
print(df[df.duplicated()])

df = df.drop_duplicates()

print("\nInformation After Removing Duplicates:")
df.info()

print("\nLast 20 Rows:")
print(df.tail(20))

#### Challenge 4 – HR Department
#### HR wants better column names.
#### Rename
#### CustomerID → Employee_ID
#### Age → EmployeeAge
#### Gender → EmployeeGender
#### AnnualIncome → Salary
#### Target → PromotionStatus
#### Then
#### • Add prefix
#### HR_
#### to every column.
#### Display 10 random records.

In [ ]:
import pandas as pd

df = pd.read_csv("C:\\Users\\HP\\Downloads\\Task_dataset - Task_dataset.csv")
df = df.rename(columns={
    "CustomerID":"Employee_ID",
    "Age":"EmployeeAge",
    "Gender":"EmployeeGender",
    "AnnualIncome":"Salary",
    "Target":"PromotionStatus"
})
df =df.add_prefix("Hr_")
df.sample(10)

#### Challenge 5 – Finance Cleaning
#### Finance department reports missing values.
#### Tasks
#### Fill
#### AnnualIncome → Median
#### Balance → Mean
#### Age → Median
#### Then
#### Generate descriptive statistics.

In [ ]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\Task_dataset - Task_dataset.csv")

df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"]=df["Balance"].fillna(df["Balance"].mean())
df["Age"]=df["Age"].fillna(df["Age"].median())
df.describe()

#### Challenge 6 – Data Type Audit
#### The company says
#### Age and AnnualIncome are stored incorrectly.
#### Tasks
#### Convert
#### Age → int
#### AnnualIncome → float
#### Balance → float
#### Target → string
#### Print information.

In [ ]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\Task_dataset - Task_dataset.csv")
df

# Convert data types
df["Age"] = df["Age"].astype(int)
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)

# Print dataset information
df.info()

#### Challenge 7 – Customer Analytics
#### Create a new DataFrame that
#### • removes Segment
#### • removes Geography
#### • removes duplicate rows
#### Display
#### • first 10 rows
#### • dataset information
#### • statistical summary

In [ ]:
df.head()
df.info()
df.describe()

#### Challenge 8 – ML Dataset Preparation
#### Prepare a machine learning dataset.
#### Perform
#### • Remove duplicates
#### • Remove CustomerID
#### • Remove Segment
#### • Fill missing values
#### • Rename Target to Output
#### Finally
#### Display
#### head()
#### info()
#### describe()
#### value_counts(Output)

In [ ]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\Task_dataset - Task_dataset.csv")
df

df = df.drop_duplicates()

df = df.drop(columns=["CustomerID", "Segment"])

df = df.fillna(df.median(numeric_only=True))

df = df.rename(columns={
    "Target": "Output"
})

print("First 5 Rows:")
print(df.head())

df.info()

print(df.describe())

print(df["Output"].value_counts())

#### Challenge 9 – Column Transformation
#### Create these new columns
#### NetWorth = Balance + AnnualIncome
#### AgeAfterRetirement = Age + 20
#### DoubleCreditScore = CreditScore * 2
#### IncomePerMonth = AnnualIncome / 12
#### Then
#### Display first 15 rows.

In [75]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\Task_dataset - Task_dataset.csv")
df
df["NetWorth"] = df["Balance"] + df["AnnualIncome"]
df["AgeAfterRetirement"] = df["Age"] + 20
df["DoubleCreditScore"] = df["CreditScore"] * 2
df["IncomePerMonth"] = df["AnnualIncome"] / 12
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay,138635.62,89.0,1540,2615.833333
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn,220598.72,78.0,1782,15178.416667
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay,269157.73,87.0,1076,7988.416667
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay,104539.41,61.0,1326,5219.833333
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,286507.98,42.0,950,14973.333333
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay,231695.03,NaN,1740,15647.666667
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn,115931.72,89.0,1148,8557.833333
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay,179444.32,79.0,1538,12572.500000
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay,174562.77,72.0,1796,7406.333333
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn,304725.43,46.0,786,12797.416667

#### Challenge 10 – Company Report
#### Display
#### • first five rows
#### • last five rows
#### • ten random rows
#### • dataset information
#### • descriptive statistics
#### Finally rename
#### Target → Customer_Status

In [77]:
df.head(50)
df.tail(5)
df.sample(10)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          1020 non-null   int64
 1   Age                 970 non-null    float64
 2   AnnualIncome        967 non-null    float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             969 non-null    float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Target              1020 non-null   object
 11  NetWorth            920 non-null    float64
 12  AgeAfterRetirement  970 non-null    float64
 13  DoubleCreditScore   1020 non-null   int64
 14  IncomePerMonth      967 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000,920.000000,970.000000,1020.000000,967.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765,209641.594380,64.249485,1205.319608,9375.494054
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330,74287.727616,15.521935,353.121379,4358.613545
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,33432.390000,38.000000,600.000000,1685.583333
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000,156965.307500,50.250000,881.500000,5512.416667
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000,209204.760000,64.000000,1214.000000,9363.166667
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000,261256.997500,78.000000,1514.500000,13166.708333
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,390628.400000,90.000000,1800.000000,16663.916667

#### Challenge 11 – Missing Value Report
#### Create a report showing
#### • Total missing values
#### • Numerical columns
#### • Mean of Balance
#### • Median of Age
#### • Fill missing values
#### • Display information again

In [81]:
print(df.isnull().sum())

print(df.select_dtypes(include="number").columns)

print(df["Balance"].mean())

print(df["Age"].median())

df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Age"] = df["Age"].fillna(df["Age"].median())

numeric_columns = df.select_dtypes(include="number").columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].mean())

df.info()

CustomerID             0
Age                    0
AnnualIncome           0
Spending               0
CreditScore            0
Balance                0
Tenure                 0
Geography             51
Gender                52
Segment               51
Target                 0
NetWorth               0
AgeAfterRetirement     0
DoubleCreditScore      0
IncomePerMonth         0
dtype: int64
Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'NetWorth', 'AgeAfterRetirement',
       'DoubleCreditScore', 'IncomePerMonth'],
      dtype='object')
97523.53566563467
44.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          1020 non-null   int64
 1   Age                 1020 non-null   float64
 2   AnnualIncome        1020 non-null   float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             1020 non-null   float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Target              1020 non-null   object
 11  NetWorth            1020 non-null   float64
 12  AgeAfterRetirement  1020 non-null   float64
 13  DoubleCreditScore   1020 non-null   int64
 14  IncomePerMonth      1020 non-null   float64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB

#### Challenge 12 – Customer Classification
#### Count
#### Stay
#### Churn
#### Then
#### Rename
#### Target → Customer_Class
#### Convert it into string.