#### 1. Load the Flight Price dataset into a Pandas DataFrame and display the first
### five rows.

In [78]:
import pandas as pd
df=pd.read_csv("C:\\Users\\HP\\Downloads\\Data_Train.xlsx - Sheet1.csv")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [79]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

#### 2.Find the number of rows and columns in the dataset.

In [80]:
df.shape

(10683, 11)

#### 3. Display all column names in the dataset.

In [81]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

#### 4. Display the data types of all columns.

In [82]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

#### 5. Use df.info() to inspect the structure of the dataset.

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

#### 6. Check the number of missing values in each column.

In [84]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

#### 7. Check the percentage of missing values in each column.

In [85]:
(df.isnull().sum()/len(df))*100

Airline            0.000000
Date_of_Journey    0.000000
Source             0.000000
Destination        0.000000
Route              0.009361
Dep_Time           0.000000
Arrival_Time       0.000000
Duration           0.000000
Total_Stops        0.009361
Additional_Info    0.000000
Price              0.000000
dtype: float64

#### 8. Display the unique values and frequency of each value in the Airline column.

In [86]:
df['Airline'].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

#### 9. Display the frequency distribution of Total_Stops, including missing values.

In [87]:
df['Total_Stops'].describe()

count      10682
unique         5
top       1 stop
freq        5625
Name: Total_Stops, dtype: object

#### 10.Convert Date_of_Journey into a datetime format.

In [88]:
df['Date_of_Journey']=pd.to_datetime(df['Date_of_Journey'])
df['Date_of_Journey']

C:\Users\HP\AppData\Local\Temp\ipykernel_24124\312018990.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date_of_Journey']=pd.to_datetime(df['Date_of_Journey'])

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
           ...
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10683, dtype: datetime64[ns]

#### 11.Extract the day from Date_of_Journey and create a day column.

In [89]:
df['day'] = pd.to_datetime(df['Date_of_Journey']).dt.day
df['day']

0        24
1         1
2         9
3        12
4         1
         ..
10678     9
10679    27
10680    27
10681     1
10682     9
Name: day, Length: 10683, dtype: int32

#### 12.Extract the month from Date_of_Journey and create a month column.

In [90]:
df['month'] = pd.to_datetime(df['Date_of_Journey']).dt.month
df['month']

0        3
1        5
2        6
3        5
4        3
        ..
10678    4
10679    4
10680    4
10681    3
10682    5
Name: month, Length: 10683, dtype: int32

#### 13.Extract the year from Date_of_Journey and create a year column.

In [91]:
df['year'] = pd.to_datetime(df['Date_of_Journey']).dt.year
df['year']

0        2019
1        2019
2        2019
3        2019
4        2019
         ...
10678    2019
10679    2019
10680    2019
10681    2019
10682    2019
Name: year, Length: 10683, dtype: int32

#### 14.Drop the original Date_of_Journey column after extracting the required features.

In [92]:
df.drop('Date_of_Journey',axis=1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

#### 15.Convert Dep_Time into datetime format and extract the departure hour into Dep_Hour.

In [93]:
df['Dep_Time']=pd.to_datetime(df["Dep_Time"],format="%H:%M")
df['Dep_Time']

0       1900-01-01 22:20:00
1       1900-01-01 05:50:00
2       1900-01-01 09:25:00
3       1900-01-01 18:05:00
4       1900-01-01 16:50:00
                ...
10678   1900-01-01 19:55:00
10679   1900-01-01 20:45:00
10680   1900-01-01 08:20:00
10681   1900-01-01 11:30:00
10682   1900-01-01 10:55:00
Name: Dep_Time, Length: 10683, dtype: datetime64[ns]

#### 16.Extract the departure minute from Dep_Time and create Dep_Minute.

In [94]:
df['Dep_Minute']=pd.to_datetime(df['Dep_Time']).dt.minute
df['Dep_Minute']

0        20
1        50
2        25
3         5
4        50
         ..
10678    55
10679    45
10680    20
10681    30
10682    55
Name: Dep_Minute, Length: 10683, dtype: int32

#### 17.Drop the original Dep_Time column after extracting the required features.

In [95]:
df.drop('Dep_Time',axis=1)

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Minute
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,20
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,50
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,25
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,12,5,2019,5
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,1,3,2019,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,22:25,2h 30m,non-stop,No info,4107,9,4,2019,55
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,23:20,2h 35m,non-stop,No info,4145,27,4,2019,45
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,11:20,3h,non-stop,No info,7229,27,4,2019,20
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,14:10,2h 40m,non-stop,No info,12648,1,3,2019,30
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,19:15,8h 20m,2 stops,No info,11753,9,5,2019,55

#### 18.Extract only the time portion from Arrival_Time.

In [96]:
df['time'] = pd.to_datetime(df['Arrival_Time']).dt.time
df['time']

C:\Users\HP\AppData\Local\Temp\ipykernel_24124\3690631915.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['time'] = pd.to_datetime(df['Arrival_Time']).dt.time

0        01:10:00
1        13:15:00
2        04:25:00
3        23:30:00
4        21:35:00
           ...
10678    22:25:00
10679    23:20:00
10680    11:20:00
10681    14:10:00
10682    19:15:00
Name: time, Length: 10683, dtype: object

#### 19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.

In [98]:
df["Arrival_Time"] = pd.to_datetime(
    df["Arrival_Time"],
    format="%H:%M",
    errors="coerce"
)

df["Arrival_Hour"] = df["Arrival_Time"].dt.hour
df["Arrival_Minute"] = df["Arrival_Time"].dt.minute
df["Arrival_Hour"]
df["Arrival_Minute"]

0         NaN
1        15.0
2         NaN
3        30.0
4        35.0
         ...
10678    25.0
10679    20.0
10680    20.0
10681    10.0
10682    15.0
Name: Arrival_Minute, Length: 10683, dtype: float64

#### 20.Drop the original Arrival_Time column after extracting the required features.

In [99]:
df.drop("Arrival_Time", axis=1)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Minute,time,Arrival_Hour,Arrival_Minute
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,1900-01-01 22:20:00,2h 50m,non-stop,No info,3897,24,3,2019,20,01:10:00,NaN,NaN
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,1900-01-01 05:50:00,7h 25m,2 stops,No info,7662,1,5,2019,50,13:15:00,13.0,15.0
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,1900-01-01 09:25:00,19h,2 stops,No info,13882,9,6,2019,25,04:25:00,NaN,NaN
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,1900-01-01 18:05:00,5h 25m,1 stop,No info,6218,12,5,2019,5,23:30:00,23.0,30.0
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,1900-01-01 16:50:00,4h 45m,1 stop,No info,13302,1,3,2019,50,21:35:00,21.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,1900-01-01 19:55:00,2h 30m,non-stop,No info,4107,9,4,2019,55,22:25:00,22.0,25.0
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,1900-01-01 20:45:00,2h 35m,non-stop,No info,4145,27,4,2019,45,23:20:00,23.0,20.0
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,1900-01-01 08:20:00,3h,non-stop,No info,7229,27,4,2019,20,11:20:00,11.0,20.0
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,1900-01-01 11:30:00,2h 40m,non-stop,No info,12648,1,3,2019,30,14:10:00,14.0,10.0
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,1900-01-01 10:55:00,8h 20m,2 stops,No info,11753,9,5,2019,55,19:15:00,19.0,15.0

#### 21.Extract the hour component from Duration and create Duration_Hour. Handle
#### invalid or missing extracted values appropriately.

In [104]:
df["Duration_Hour"]=(df["Duration"].astype(str).str.extract(r"(\d+)\s*h", expand=False))
df["Duration_Hour"] =pd.to_numeric(df["Duration_Hour"],errors="coerce")
print(df[["Duration", "Duration_Hour"]])

      Duration  Duration_Hour
0       2h 50m            2.0
1       7h 25m            7.0
2          19h           19.0
3       5h 25m            5.0
4       4h 45m            4.0
...        ...            ...
10678   2h 30m            2.0
10679   2h 35m            2.0
10680       3h            3.0
10681   2h 40m            2.0
10682   8h 20m            8.0

[10683 rows x 2 columns]

#### 22.Extract the minute component from Duration and create Duration_Minute.
#### Handle invalid or missing extracted values appropriately.

In [105]:
df["Duration_Minute"] = (
    df["Duration"]
    .astype(str)
    .str.extract(r"(\d+)\s*m", expand=False)
)

df["Duration_Minute"] = pd.to_numeric(
    df["Duration_Minute"],
    errors="coerce"
)
print(df[["Duration", "Duration_Minute"]])

      Duration  Duration_Minute
0       2h 50m             50.0
1       7h 25m             25.0
2          19h              NaN
3       5h 25m             25.0
4       4h 45m             45.0
...        ...              ...
10678   2h 30m             30.0
10679   2h 35m             35.0
10680       3h              NaN
10681   2h 40m             40.0
10682   8h 20m             20.0

[10683 rows x 2 columns]

#### 23.Drop the original Duration column after creating the numerical duration
#### features.

In [106]:
df.drop("Duration", axis=1)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Total_Stops,Additional_Info,Price,day,month,year,Dep_Minute,time,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,1900-01-01 22:20:00,NaT,non-stop,No info,3897,24,3,2019,20,01:10:00,NaN,NaN,2.0,50.0
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,1900-01-01 05:50:00,1900-01-01 13:15:00,2 stops,No info,7662,1,5,2019,50,13:15:00,13.0,15.0,7.0,25.0
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,1900-01-01 09:25:00,NaT,2 stops,No info,13882,9,6,2019,25,04:25:00,NaN,NaN,19.0,NaN
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,1900-01-01 18:05:00,1900-01-01 23:30:00,1 stop,No info,6218,12,5,2019,5,23:30:00,23.0,30.0,5.0,25.0
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,1900-01-01 16:50:00,1900-01-01 21:35:00,1 stop,No info,13302,1,3,2019,50,21:35:00,21.0,35.0,4.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,1900-01-01 19:55:00,1900-01-01 22:25:00,non-stop,No info,4107,9,4,2019,55,22:25:00,22.0,25.0,2.0,30.0
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,1900-01-01 20:45:00,1900-01-01 23:20:00,non-stop,No info,4145,27,4,2019,45,23:20:00,23.0,20.0,2.0,35.0
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,1900-01-01 08:20:00,1900-01-01 11:20:00,non-stop,No info,7229,27,4,2019,20,11:20:00,11.0,20.0,3.0,NaN
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,1900-01-01 11:30:00,1900-01-01 14:10:00,non-stop,No info,12648,1,3,2019,30,14:10:00,14.0,10.0,2.0,40.0
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,1900-01-01 10:55:00,1900-01-01 19:15:00,2 stops,No info,11753,9,5,2019,55,19:15:00,19.0,15.0,8.0,20.0

#### 24.Replace non-stop in Total_Stops with 0 stops.

In [107]:
df = pd.DataFrame({'Total_Stops': ['non-stop', '1 stop', '2 stops', 'non-stop']})
df['Total_Stops'] = df['Total_Stops'].replace('non-stop', '0 stops')
df['Total_Stops']

0    0 stops
1     1 stop
2    2 stops
3    0 stops
Name: Total_Stops, dtype: object

#### 25.Extract only the numerical value from Total_Stops and convert the column into
#### an integer data type. Handle missing or invalid values appropriately.

In [110]:

df["Total_Stops"] = (df["Total_Stops"].astype(str).str.extract(r"(\d+)", expand=False))

df["Total_Stops"] = pd.to_numeric(df["Total_Stops"], errors="coerce")

df["Total_Stops"] = df["Total_Stops"].fillna(0)

df["Total_Stops"] = df["Total_Stops"].astype(int)

print(df["Total_Stops"].head())
print(df["Total_Stops"].dtype)

0    1
1    2
2    0
3    0
4    3
Name: Total_Stops, dtype: int64
int64