In [3]:
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Vikas", "Neha"],
    "Age": [22, 25, 21, 24, 28, 23],
    "City": ["Pune", "Mumbai", "Nagpur", "Pune", "Mumbai", "Nagpur"],
    "Salary": [30000, 45000, 28000, 40000, 55000, 35000],
    "Experience": [1, 3, 0, 2, 5, 1]
}

df = pd.DataFrame(data)

print(df)

    Name  Age    City  Salary  Experience
0   Amit   22    Pune   30000           1
1  Priya   25  Mumbai   45000           3
2  Rahul   21  Nagpur   28000           0
3  Sneha   24    Pune   40000           2
4  Vikas   28  Mumbai   55000           5
5   Neha   23  Nagpur   35000           1

In [ ]:
Q21. Display the first 3 rows.

Q22. Display the last 2 rows.

Q23. Find the number of rows and columns.

Q24. Display all column names.

Q25. Find the data types.

Q26. Find the average salary.

Q27. Find the highest salary.

Q28. Find the lowest salary.

Q29. Find the average age.

Q30. Find employees whose salary is greater than 40,000.

In [2]:
df.head(3)

    Name  Age    City  Salary  Experience
0   Amit   22    Pune   30000           1
1  Priya   25  Mumbai   45000           3
2  Rahul   21  Nagpur   28000           0

In [3]:
df.tail(2)

    Name  Age    City  Salary  Experience
4  Vikas   28  Mumbai   55000           5
5   Neha   23  Nagpur   35000           1

In [4]:
df.shape

(6, 5)

In [5]:
df.columns

Index(['Name', 'Age', 'City', 'Salary', 'Experience'], dtype='object')

In [7]:
df.dtypes

Name          object
Age            int64
City          object
Salary         int64
Experience     int64
dtype: object

In [22]:
print(df['Salary'].mean())

38833.333333333336

In [21]:
print(df['Salary'].max())

55000

In [20]:
print(df['Salary'].min())

28000

In [19]:
print(df['Age'].mean())

23.833333333333332

In [18]:
print(df[df["Salary"] > 40000])

    Name  Age    City  Salary  Experience
1  Priya   25  Mumbai   45000           3
4  Vikas   28  Mumbai   55000           5

In [23]:
df[df["City"] == "Pune"]

    Name  Age  City  Salary  Experience
0   Amit   22  Pune   30000           1
3  Sneha   24  Pune   40000           2

In [ ]:
Q32

Find employees from Mumbai with salary greater than 40,000.

Q33

Find employees whose age is greater than 23.

Q34

Find employees with experience greater than or equal to 2 years.

Q35

Find employees from either Pune or Nagpur.

Q36

Find employees whose salary is between 30,000 and 50,000.

In [24]:
df[(df["City"]=="Mumbai")&(df["Salary"]>40000)]

    Name  Age    City  Salary  Experience
1  Priya   25  Mumbai   45000           3
4  Vikas   28  Mumbai   55000           5

In [27]:
df[(df["City"]=="Pune")&(df["Age"]>20)]

    Name  Age  City  Salary  Experience
0   Amit   22  Pune   30000           1
3  Sneha   24  Pune   40000           2

In [28]:
df[(df["Age"]>23)]

    Name  Age    City  Salary  Experience
1  Priya   25  Mumbai   45000           3
3  Sneha   24    Pune   40000           2
4  Vikas   28  Mumbai   55000           5

In [30]:
df[(df["Experience"]>=2)]

    Name  Age    City  Salary  Experience
1  Priya   25  Mumbai   45000           3
3  Sneha   24    Pune   40000           2
4  Vikas   28  Mumbai   55000           5

In [4]:
df[df["City"].isin(["Pune", "Nagpur"])]

    Name  Age    City  Salary  Experience
0   Amit   22    Pune   30000           1
2  Rahul   21  Nagpur   28000           0
3  Sneha   24    Pune   40000           2
5   Neha   23  Nagpur   35000           1

In [5]:
df[df["Salary"].between(30000,50000)]

    Name  Age    City  Salary  Experience
0   Amit   22    Pune   30000           1
1  Priya   25  Mumbai   45000           3
3  Sneha   24    Pune   40000           2
5   Neha   23  Nagpur   35000           1

In [4]:
df["Annual_Salary"]=df["Salary"]*12
print(df)

    Name  Age    City  Salary  Experience  Annual_Salary
0   Amit   22    Pune   30000           1         360000
1  Priya   25  Mumbai   45000           3         540000
2  Rahul   21  Nagpur   28000           0         336000
3  Sneha   24    Pune   40000           2         480000
4  Vikas   28  Mumbai   55000           5         660000
5   Neha   23  Nagpur   35000           1         420000

In [5]:
def experience_level(exp):
    if exp==0:
        return "Fresher"
    elif exp <= 2:
        return "Junior"
    else :
        return "Senior"
df["Experience_level"]=df["Experience"].apply(experience_level)
print(df)

    Name  Age    City  Salary  Experience  Annual_Salary Experience_level
0   Amit   22    Pune   30000           1         360000           Junior
1  Priya   25  Mumbai   45000           3         540000           Senior
2  Rahul   21  Nagpur   28000           0         336000          Fresher
3  Sneha   24    Pune   40000           2         480000           Junior
4  Vikas   28  Mumbai   55000           5         660000           Senior
5   Neha   23  Nagpur   35000           1         420000           Junior

In [6]:
df_sorted=df.sort_values(
    by="Salary",
    ascending=False
)
print(df_sorted)

    Name  Age    City  Salary  Experience  Annual_Salary Experience_level
4  Vikas   28  Mumbai   55000           5         660000           Senior
1  Priya   25  Mumbai   45000           3         540000           Senior
3  Sneha   24    Pune   40000           2         480000           Junior
5   Neha   23  Nagpur   35000           1         420000           Junior
0   Amit   22    Pune   30000           1         360000           Junior
2  Rahul   21  Nagpur   28000           0         336000          Fresher

In [8]:
df_sorted=df.sort_values(
    by="Age",
    ascending=True
)
print(df_sorted)

    Name  Age    City  Salary  Experience  Annual_Salary Experience_level
2  Rahul   21  Nagpur   28000           0         336000          Fresher
0   Amit   22    Pune   30000           1         360000           Junior
5   Neha   23  Nagpur   35000           1         420000           Junior
3  Sneha   24    Pune   40000           2         480000           Junior
1  Priya   25  Mumbai   45000           3         540000           Senior
4  Vikas   28  Mumbai   55000           5         660000           Senior

In [15]:
df = df.rename(columns={
    "Name": "Employee_Name",
    "Salary": "Monthly_Salary"
})
print(df)

AttributeError: 'NoneType' object has no attribute 'rename'