#### Part 1 — Inspect & Understand the Dataset
#### Q1. Load the dataset
#### Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
#### Then display the first 10 rows.
#### Use: pd.read_csv(), head()

In [48]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\customer_analytics - customer_analytics.csv")
print(df)
df.head(10)

      Customer_ID Age Annual_Income Account_Balance Credit_Score  \
0          101317  55         44033       111350.85          772
1          101001  32        215546       254378.37          374
2          101069  23        226403       159975.42          668
3          101968  66         87824        295741.6          315
4          100530  67         31570       242423.78          370
...           ...  ..           ...             ...          ...
2035       101131  42         88530       153490.72          677
2036       101295  31        205738        270989.4          392
2037       100861  25        211994       160507.65          737
2038       101460  64         30105        32117.15          794
2039       101127  55        248332       274980.99          783

      Tenure_Years       City    Segment Channel         Join_Date Active  \
0                3  Bangalore        SME   Agent  15-08-2022 00:00    Yes
1                8      Delhi     Retail   Agent  11-01-2025 00:00    Yes
2               12    Chennai    Premium   Agent  01-08-2024 00:00     No
3               14     Mumbai    Premium   Agent  15-05-2021 00:00    Yes
4                4  bangalore     Retail   Agent  03-02-2026 00:00     No
...            ...        ...        ...     ...               ...    ...
2035            12  Hyderabad     Retail   Agent  10-07-2021 00:00     No
2036             8     Mumbai  Corporate   Agent  05-07-2025 00:00    Yes
2037             8    Kolkata     Retail  Online  17-10-2022 00:00    Yes
2038             8  Bangalore     Retail   Agent  26-08-2023 00:00     No
2039             6    Chennai     Retail  Branch               NaN    Yes

     Risk_Level Monthly_Spend Transactions  Satisfaction_Score
0           Low      23066.19          135                 3.1
1          High           NaN          106                 8.2
2        Medium      28536.34          146                 6.3
3          High      12869.71          115                 9.7
4          High      34163.02           94                 3.7
...         ...           ...          ...                 ...
2035     Medium       8455.42          119                 8.6
2036       High      34087.69          134                 2.6
2037        Low      26518.74           87                 1.3
2038        Low      20943.11          107                 9.3
2039        Low      48511.32          119                 3.1

[2040 rows x 15 columns]

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,15-08-2022 00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,11-01-2025 00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,01-08-2024 00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,15-05-2021 00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,03-02-2026 00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,04-06-2023 00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,16-01-2024 00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,26-06-2024 00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,12-03-2025 00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,07-10-2021 00:00,Yes,Medium,11472.36,124,9.1

#### Q2. Inspect the end of the dataset
#### Display the last 15 rows.
#### Use: tail()

In [49]:
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,22-04-2022 00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,02-07-2022 00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,11-09-2024 00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,08-04-2022 00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,26-07-2023 00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,03-11-2024 00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,15-01-2026 00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,30-11-2022 00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,04-07-2021 00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,10-09-2025 00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,10-07-2021 00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,05-07-2025 00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,17-10-2022 00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,26-08-2023 00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

#### Q3. Random inspection
#### Display 10 random records.
#### Use: sample()

In [50]:
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1065,101234,66,101272,NaN,692,0,Pune,Premium,Mobile,03-05-2023 00:00,Yes,Medium,39156.19,113,1.9
1909,100065,NaN,94274,297378.97,433,10,hyderabad,NaN,Online,13-09-2021 00:00,Yes,High,11169.39,80,5.9
110,101023,34,123723,111972.35,820,2,Bangalore,Premium,Agent,13-05-2022 00:00,Yes,Low,30264.76,136,1.8
1640,100230,61,72837,245939.34,411,1,Pune,Premium,Branch,10-01-2024 00:00,Yes,High,41591.88,125,8.0
1268,100358,52,239919,missing,818,7,Bangalore,Retail,Online,11-01-2022 00:00,No,Low,43378.56,104,7.4
1830,101110,NaN,246972,280071.33,743,14,Bangalore,Premium,Mobile,20-07-2022 00:00,No,Low,13241.86,26,5.1
1875,100805,45,135944,missing,442,10,Delhi,SME,Branch,27-11-2023 00:00,Yes,High,29544.36,87,4.5
223,100232,32,53541,219915.36,642,3,Kolkata,Retail,Branch,05-03-2026 00:00,No,Medium,11377.64,72,3.0
995,101967,58,36190,135625.98,571,9,Kolkata,SME,Branch,31-10-2021 00:00,Yes,Medium,8247.14,105,5.2
546,100335,58,106941,169388.72,792,5,Chennai,Premium,Branch,22-04-2023 00:00,Yes,Low,13546.86,46,6.3

#### Q4. Dataset audit
#### Use info() to identify:
#### • Number of rows
#### • Number of columns
#### • Columns with missing values
#### • Columns having incorrect/object datatypes
#### Use: info()

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

#### Q5. Missing-value audit
#### Calculate the number of missing values in every column.
#### Then verify the result using both:
#### isnull()#### 
#### and
#### isna()

In [52]:
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

#### Part 2 — Detect & Fix Data Quality Problems
#### Q6. Duplicate investigation
#### Find how many duplicate rows exist.
#### Do not remove them yet.
#### Use: duplicated()

In [53]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2040, dtype: bool

#### Q7. Remove duplicates
#### Remove all duplicate records and store the cleaned result back into df.
#### Then verify that duplicates no longer exist.
#### Use: drop_duplicates(), duplicated()

In [54]:
df.drop_duplicates()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,15-08-2022 00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,11-01-2025 00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,01-08-2024 00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,15-05-2021 00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,03-02-2026 00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,10-07-2021 00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,05-07-2025 00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,17-10-2022 00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,26-08-2023 00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [55]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2040, dtype: bool

#### Q8. Numeric column investigation
#### Select only numeric columns.
#### Identify which columns are currently numeric and which potentially numeric columns have
#### become object because of invalid values.
#### Use: select_dtypes()

In [56]:
df = df.select_dtypes(include="number")
df.columns
df.head()

   Customer_ID  Tenure_Years  Satisfaction_Score
0       101317             3                 3.1
1       101001             8                 8.2
2       101069            12                 6.3
3       101968            14                 9.7
4       100530             4                 3.7

#### Q9. Fix Age
#### The Age column contains:
#### • Valid numbers
#### • Missing values
#### • Invalid text such as unknown, N/A, etc.
#### Convert Age into a proper numeric column.
#### Invalid values should become missing values.
#### Then fill missing Age values using the median age.
#### Use: pd.to_numeric(), median(), fillna()

In [57]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\customer_analytics - customer_analytics.csv")
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"]

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2040, dtype: float64

In [58]:
df["Age"].median()

47.0

In [59]:

df["Age"].dtype

dtype('float64')

In [60]:
df["Age"].dtype

dtype('float64')

#### Q10. Fix Annual Income
#### Clean Annual_Income.
#### Requirements:
#### 1. Convert invalid values to missing.
#### 2. Convert the column to a numeric datatype.
#### 3. Calculate the median.
#### 4. Fill missing values using the median.
#### Use: pd.to_numeric(), median(), fillna(), astype()

In [63]:
df["Annual_Income"]= pd.to_numeric(df["Annual_Income"], errors="coerce")

df["Annual_Income"]= df["Annual_Income"].astype(float)

median= df["Annual_Income"].median()

df["Annual_Income"]= df["Annual_Income"].fillna(median)

df["Annual_Income"]

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2040, dtype: float64

#### Part 3 — Numerical Cleaning
#### Q11. Clean Account Balance
#### The Account_Balance column contains invalid strings and missing values.
#### Clean the column and replace missing values with the mean Account Balance.
#### Use:
#### • pd.to_numeric()
#### • mean()
#### • fillna()

In [65]:
df["Annual_Income"]= pd.to_numeric(df["Annual_Income"], errors="coerce")
mean= df["Annual_Income"].mean()
df["Annual_Income"]= df["Annual_Income"].fillna(mean)
df["Annual_Income"]

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2040, dtype: float64

#### Q12. Clean Credit Score
#### Clean Credit_Score.
#### Invalid values should become missing.
#### Then replace missing values with the median Credit Score.
#### Finally convert the column to integer.
#### Use:
#### • pd.to_numeric()
#### • median()
#### • fillna()
#### • astype()

In [66]:
df["Credit_Score"] =pd.to_numeric(df["Credit_Score"], errors="coerce")
df["Credit_Score"] =df["Credit_Score"].fillna(df["Credit_Score"].median())
df["Credit_Score"] =df["Credit_Score"].astype(int)
df["Credit_Score"]

0       772
1       374
2       668
3       315
4       370
       ...
2035    677
2036    392
2037    737
2038    794
2039    783
Name: Credit_Score, Length: 2040, dtype: int64

#### Q13. Clean Monthly Spend
#### Clean Monthly_Spend.
#### Then:
#### • Convert it to numeric.
#### • Replace invalid values.
#### • Replace missing values using the median.
#### • Make sure the final column is numeric.

In [67]:
df["Monthly_Spend"] =pd.to_numeric(df["Monthly_Spend"], errors="coerce")
df["Monthly_Spend"] =df["Monthly_Spend"].fillna(df["Monthly_Spend"].median())
df["Monthly_Spend"] =df["Monthly_Spend"].astype(float)
df["Monthly_Spend"]

0       23066.19
1       24646.77
2       28536.34
3       12869.71
4       34163.02
          ...
2035     8455.42
2036    34087.69
2037    26518.74
2038    20943.11
2039    48511.32
Name: Monthly_Spend, Length: 2040, dtype: float64

#### Q14. Clean Transactions
#### The Transactions column contains invalid strings.
#### Convert it to numeric and replace invalid values with the median number of transactions.
#### Then convert the final column to integer.

In [68]:
df["Transactions"] =pd.to_numeric(df["Transactions"], errors="coerce")
df["Transactions"] =df["Transactions"].fillna(df["Transactions"].median())
df["Transactions"] =df["Transactions"].astype(int)
df["Transactions"]

0       135
1       106
2       146
3       115
4        94
       ...
2035    119
2036    134
2037     87
2038    107
2039    119
Name: Transactions, Length: 2040, dtype: int64

#### Q15. Clean Satisfaction Score
#### Clean Satisfaction_Score.
#### Replace missing/invalid values using the mean Satisfaction Score.
#### Then convert the column to float.

In [69]:
df["Satisfaction_Score"] = pd.to_numeric(df["Satisfaction_Score"], errors="coerce")

df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(df["Satisfaction_Score"].mean())

df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)
df["Satisfaction_Score"]

0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2040, dtype: float64

#### Part 4 — Date Cleaning
#### Q16. Investigate Join_Date
#### Inspect the Join_Date column.
#### Identify the problems caused by:
#### • Missing dates
#### • Different date formats
#### • Invalid date strings
#### Do not clean it yet.

In [70]:
print("Datatype:", df["Join_Date"].dtype)
print("Missing values:", df["Join_Date"].isna().sum())
print("Unique values:")
print(df["Join_Date"].dropna().unique())

Datatype: object
Missing values: 102
Unique values:
['15-08-2022 00:00' '11-01-2025 00:00' '01-08-2024 00:00' ...
 '10-09-2025 00:00' '17-10-2022 00:00' '26-08-2023 00:00']

#### Q17. Convert Join_Date
#### Convert Join_Date into a proper Pandas datetime column.
#### Any invalid dates should become missing values.
#### Use: pd.to_datetime()

In [71]:
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce",
    dayfirst=True
)

print(df["Join_Date"])
print(df["Join_Date"].dtype)

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039          NaT
Name: Join_Date, Length: 2040, dtype: datetime64[ns]
datetime64[ns]

#### Q18. Handle missing dates
#### After conversion, find how many missing dates remain.
#### Then replace missing dates appropriately using a reasonable date-based strategy.

In [72]:
print(df["Join_Date"].isna().sum())
df["Join_Date"] = df["Join_Date"].fillna(df["Join_Date"].median())

128

#### Part 5 — Categorical Cleaning
#### Q19. Clean City
#### The City column contains values such as:
#### Mumbai
#### mumbai
#### Mumbai
#### mumbai
#### Standardize the values so that logically identical cities are represented consistently.
#### Then check the unique frequency distribution.
#### Use: replace(), value_counts()

In [73]:
df["City"] = df["City"].replace({
    "mumbai": "Mumbai",
    "MUMBAI": "Mumbai"
})

print(df["City"].value_counts())

City
Mumbai       314
Hyderabad    278
Delhi        273
Kolkata      262
Pune         256
Chennai      242
Bangalore    236
hyderabad     20
bangalore     18
pune          18
delhi         15
kolkata       14
chennai       13
Name: count, dtype: int64

#### Q20. Analyze Segment
#### Check the frequency of:
#### Retail
#### SME
#### Corporate
#### Premium
#### Also determine whether missing values exist.
#### Then replace missing Segment values with the most appropriate category based on your
#### analysis.
#### Use: value_counts(), fillna()

In [74]:
df["Segment"].value_counts()
df["Segment"].isna().sum()
df["Segment"] = df["Segment"].fillna(df["Segment"].mode()[0])
df["Segment"].value_counts()

Segment
Premium      628
Retail       481
Corporate    475
SME          456
Name: count, dtype: int64

#### Q21. Clean Active
#### Active is supposed to be a binary column, but it contains:
#### Yes
#### No
#### Y
#### N
#### YES
#### NO
#### yes
#### no
#### 1
#### 0
#### Transform these into a consistent representation:
#### Yes
#### No
#### Then verify the result with value_counts().
#### Use: replace(), value_counts()

In [75]:
df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    "1": "Yes",
    1: "Yes",

    "N": "No",
    "NO": "No",
    "no": "No",
    "0": "No",
    0: "No"
})

print(df["Active"].value_counts())

Active
Yes    1371
No      610
Name: count, dtype: int64

#### Q22. Clean Risk_Level
#### Check the distribution of:
#### High
#### Medium
#### Low
#### 
#### Sumit Sir Notes
#### Verify whether missing values exist.
#### Then display the final class distribution.

In [76]:
df["Risk_Level"].value_counts()

df["Risk_Level"].isna().sum()
df["Risk_Level"]

0          Low
1         High
2       Medium
3         High
4         High
         ...
2035    Medium
2036      High
2037       Low
2038       Low
2039       Low
Name: Risk_Level, Length: 2040, dtype: object

#### Q23. Rename columns
#### Rename these columns:
#### Customer_ID → Customer_ID
#### Annual_Income → AnnualIncome
#### Account_Balance → AccountBalance
#### Credit_Score → CreditScore
#### Tenure_Years → Tenure
#### Join_Date → CustomerJoinDate
#### Risk_Level → RiskLevel
#### Monthly_Spend → MonthlySpend
#### Satisfaction_Score → SatisfactionScore
#### Use rename().

In [77]:
df = df.rename(columns={
    "Customer_ID": "Customer_ID",
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
})

print(df.columns)

Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore'],
      dtype='object')

#### Add:
#### Customer_
#### to every column.
#### Example:
#### Age
#### becomes:
#### Customer_Age
#### Use: add_prefix()

In [78]:
df = df.add_prefix("Customer_")
df

,Customer_Customer_ID,Customer_Age,Customer_AnnualIncome,Customer_AccountBalance,Customer_CreditScore,Customer_Tenure,Customer_City,Customer_Segment,Customer_Channel,Customer_CustomerJoinDate,Customer_Active,Customer_RiskLevel,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646.77,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26 12:00:00,Yes,Low,48511.32,119,3.1

#### Q25. Remove unnecessary column
#### Determine whether Customer_ID should be retained for analysis.
#### Create a cleaned DataFrame without the identifier column.
#### Use: drop()

In [84]:
df_clean = df.drop(columns=["Customer_Customer_ID"])
df_clean

,Customer_Age,Customer_AnnualIncome,Customer_AccountBalance,Customer_CreditScore,Customer_Tenure,Customer_City,Customer_Segment,Customer_Channel,Customer_CustomerJoinDate,Customer_Active,Customer_RiskLevel,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore
0,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646.77,106,8.2
2,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26 12:00:00,Yes,Low,48511.32,119,3.1

In [92]:
df.to_csv("Clean_Data.csv", index=False)